// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnwiLkTH3SlW_5yUnXwX5-1IprkV3R_EQ',
    appId: '1:880048569191:web:7fd68dc60f08e3512d8dc2',
    messagingSenderId: '880048569191',
    projectId: 'godiknowyougotthisthankyou',
    authDomain: 'godiknowyougotthisthankyou.firebaseapp.com',
    storageBucket: 'godiknowyougotthisthankyou.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGkxM7AfOvcxrUvW0syGHVLYCcv_m6y5c',
    appId: '1:880048569191:android:0b15f22921147b362d8dc2',
    messagingSenderId: '880048569191',
    projectId: 'godiknowyougotthisthankyou',
    storageBucket: 'godiknowyougotthisthankyou.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd8bYcV2Xb6uUCUtudVjjt6gEaPxpz2DE',
    appId: '1:880048569191:ios:58f0bd0389833f812d8dc2',
    messagingSenderId: '880048569191',
    projectId: 'godiknowyougotthisthankyou',
    storageBucket: 'godiknowyougotthisthankyou.appspot.com',
    iosClientId: '880048569191-fh0bmeh7j7q1m1jr6sr4bepf71be3fug.apps.googleusercontent.com',
    iosBundleId: 'com.example.postvehicles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd8bYcV2Xb6uUCUtudVjjt6gEaPxpz2DE',
    appId: '1:880048569191:ios:33bef2d38e3a98952d8dc2',
    messagingSenderId: '880048569191',
    projectId: 'godiknowyougotthisthankyou',
    storageBucket: 'godiknowyougotthisthankyou.appspot.com',
    iosClientId: '880048569191-bktu5gdcepvpam7oc92k8jm8kjg0vtnu.apps.googleusercontent.com',
    iosBundleId: 'com.example.postvehicles.RunnerTests',
  );
}
